In [4]:
import pandas as pd
import pickle
import numpy as np

In [3]:
model = pickle.load(open('models/decision_tree_model.pkl', 'rb'))
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_emb = pickle.load(open('models/ohe_emb.pkl', 'rb'))
scalar_age = pickle.load(open('models/scalar_age.pkl', 'rb'))
scalar_fare = pickle.load(open('models/scalar_fare.pkl', 'rb'))

In [10]:
test_input = np.array([1, 0, 0, 32, 30, 'S', 'male'], dtype=object).reshape(1, 7)
test_input

array([[1, 0, 0, 32, 30, 'S', 'male']], dtype=object)

In [11]:
test_input_sex = ohe_sex.transform(test_input[:, 6].reshape(1,1))
test_input_sex

c:\Users\aryan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [12]:
test_input_emb = ohe_emb.transform(test_input[:, 5].reshape(1,1))
test_input_emb

array([[0., 0., 1.]])

In [14]:
test_input_age = scalar_age.transform(test_input[:, 3].reshape(1,1))
test_input_age

array([[0.39683338]])

In [15]:
test_input_fare = scalar_fare.transform(test_input[:, 4].reshape(1,1))
test_input_fare

c:\Users\aryan\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.0585561]])

In [19]:
test_input_transformed = np.concatenate((test_input[:, 0:3], test_input_age, test_input_fare, test_input_emb, test_input_sex), axis=1)
test_input_transformed

array([[1, 0, 0, 0.39683337521990447, 0.05855610025741262, 0.0, 0.0, 1.0,
        0.0, 1.0]], dtype=object)

In [20]:
test_input_transformed.shape

(1, 10)

In [21]:
prediction = model.predict(test_input_transformed)
prediction

array([1])

In [22]:
# Therefore, without using pipelines we need to do feature engineering in testing/production also!!
# If any step is added in feature engineering process, it needs to be added in testing/production code too, which is not desirable