In [84]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

In [85]:
df = pd.read_csv("../data/covid_toy.csv")
df.sample(5)

,age,gender,fever,cough,city,has_covid
25,23,Male,NaN,Mild,Mumbai,No
27,33,Female,102.0,Strong,Delhi,No
10,75,Female,NaN,Mild,Delhi,No
96,51,Female,101.0,Strong,Kolkata,Yes
8,19,Female,100.0,Strong,Bangalore,No


In [86]:
# Feature-Engineering to be applied ----

# Label Encoder -- on has_covid
# Ordinal Encover - on cough
# One hot encoder - on gender, city
# Standard Scaler on age, fever

In [87]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [88]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [89]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [90]:
ohe = OneHotEncoder(sparse_output=False, drop='first', dtype = np.int32)
le = LabelEncoder()
oe = OrdinalEncoder(categories=[["Mild", "Strong"]])
scalar = StandardScaler()
si = SimpleImputer()

In [91]:
X = df.drop(columns=["has_covid"])
y = df["has_covid"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [92]:
X_train

,age,gender,fever,cough,city
55,81,Female,101.0,Mild,Mumbai
88,5,Female,100.0,Mild,Kolkata
26,19,Female,100.0,Mild,Kolkata
42,27,Male,100.0,Mild,Delhi
69,73,Female,103.0,Mild,Delhi
...,...,...,...,...,...
60,24,Female,102.0,Strong,Bangalore
71,75,Female,104.0,Strong,Delhi
14,51,Male,104.0,Mild,Bangalore
92,82,Female,102.0,Strong,Kolkata


In [93]:
y_test

83     No
53    Yes
70     No
45     No
44     No
39     No
22    Yes
80    Yes
10     No
0      No
18    Yes
30    Yes
73    Yes
33     No
90     No
4      No
76    Yes
77     No
12     No
31     No
Name: has_covid, dtype: str

In [94]:
#Handling missing values

X_train_si = si.fit_transform(X_train[["fever"]])
X_test_si = si.transform(X_test[["fever"]])

In [95]:
X_train_si

array([[101.],
       [100.],
       [100.],
       [100.],
       [103.],
       [103.],
       [102.],
       [101.],
       [101.],
       [101.],
       [ 98.],
       [104.],
       [103.],
       [104.],
       [100.],
       [101.],
       [104.],
       [102.],
       [102.],
       [103.],
       [104.],
       [102.],
       [101.],
       [104.],
       [102.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [102.],
       [100.],
       [ 98.],
       [ 98.],
       [101.],
       [100.],
       [100.],
       [101.],
       [104.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 99.],
       [101.],
       [ 99.],
       [101.],
       [104.],
       [ 98.],
       [101.],
       [103.],
       [101.],
       [ 98.],
       [ 99.],
       [ 98.],
       [ 99.],
       [102.],
       [101.],
       [101.],
       [104.],
       [100.],
       [ 98.],
       [100.],
       [101.],
       [100.],
       [100.],
       [ 9

In [96]:
#Label Encoding

y_train_le = le.fit_transform(y_train)
y_test_le = le.transform(y_test)

y_test_le

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [97]:
#Ordinal Encoding

X_train_oe = oe.fit_transform(X_train[['cough']])
X_test_oe = oe.transform(X_test[['cough']])

X_train_oe

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],

In [98]:
#One-hot encoding

X_train_ohe = ohe.fit_transform(X_train[['city', 'gender']])
X_test_ohe = ohe.transform(X_test[['city', 'gender']])

X_train_ohe

array([[0, 0, 1, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 1],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 1, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1,

In [99]:
#Standard scaling

#First combining fever(after missing val) and age into a df

array_num_train = np.hstack((X_train[['age']].values, X_train_si))
array_num_test = np.hstack((X_test[['age']].values, X_test_si))

In [100]:
X_train_numerical = pd.DataFrame(array_num_train, columns =['age', 'fever'])
X_test_numerical = pd.DataFrame(array_num_test, columns =['age', 'fever'])

X_train_numerical

,age,fever
0,81.0,101.0
1,5.0,100.0
2,19.0,100.0
3,27.0,100.0
4,73.0,103.0
...,...,...
75,24.0,102.0
76,75.0,104.0
77,51.0,104.0
78,82.0,102.0


In [101]:
X_train_numerical.isnull().sum()

age      0
fever    0
dtype: int64

In [102]:
X_test_numerical.isnull().sum()

age      0
fever    0
dtype: int64

In [103]:
X_train_scaled = scalar.fit_transform(X_train_numerical)
X_test_scaled = scalar.transform(X_test_numerical)

X_train_scaled

array([[ 1.56614097,  0.        ],
       [-1.55894504, -0.52164053],
       [-0.98327131, -0.52164053],
       [-0.65431488, -0.52164053],
       [ 1.23718454,  1.04328106],
       [ 1.11382589,  1.04328106],
       [ 0.25031528,  0.52164053],
       [ 0.33255438,  0.        ],
       [ 0.86710857,  0.        ],
       [ 1.64838007,  0.        ],
       [ 0.90822812, -1.56492159],
       [-1.02439086,  1.56492159],
       [-1.10662996,  1.04328106],
       [-1.10662996,  1.56492159],
       [-0.65431488, -0.52164053],
       [ 1.68949962,  0.        ],
       [ 0.33255438,  1.56492159],
       [ 1.07270633,  0.52164053],
       [ 1.60726052,  0.52164053],
       [ 1.07270633,  1.04328106],
       [ 0.04471751,  1.56492159],
       [ 1.2783041 ,  0.52164053],
       [-0.94215175,  0.        ],
       [-1.27110817,  1.56492159],
       [-0.40759757,  0.52164053],
       [-0.03752159,  0.        ],
       [ 0.90822812, -1.04328106],
       [-0.81879309,  0.        ],
       [ 0.53815215,

In [104]:
arr_train_transformed = np.hstack((X_train_scaled, X_train_oe, X_train_ohe))
arr_test_transformed = np.hstack((X_test_scaled, X_test_oe, X_test_ohe))

arr_train_transformed

array([[ 1.56614097,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ],
       [-1.55894504, -0.52164053,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ],
       [-0.98327131, -0.52164053,  0.        ,  0.        ,  1.        ,
         0.        ,  0.        ],
       [-0.65431488, -0.52164053,  0.        ,  1.        ,  0.        ,
         0.        ,  1.        ],
       [ 1.23718454,  1.04328106,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 1.11382589,  1.04328106,  1.        ,  0.        ,  1.        ,
         0.        ,  1.        ],
       [ 0.25031528,  0.52164053,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.33255438,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        ],
       [ 0.86710857,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ],
       [ 1.64838007,  0.    

In [105]:
X_train_transformed = pd.DataFrame(arr_train_transformed, columns=['age', 'fever', 'cough_strong', 'city_delhi', 'city_kolkata', 'city_mumbai', 'gender_male'])
X_test_transformed = pd.DataFrame(arr_test_transformed, columns=['age', 'fever', 'cough_strong', 'city_delhi', 'city_kolkata', 'city_mumbai', 'gender_male'])

X_train_transformed

,age,fever,cough_strong,city_delhi,city_kolkata,city_mumbai,gender_male
0,1.566141,0.000000,0.0,0.0,0.0,1.0,0.0
1,-1.558945,-0.521641,0.0,0.0,1.0,0.0,0.0
2,-0.983271,-0.521641,0.0,0.0,1.0,0.0,0.0
3,-0.654315,-0.521641,0.0,1.0,0.0,0.0,1.0
4,1.237185,1.043281,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...
75,-0.777674,0.521641,1.0,0.0,0.0,0.0,0.0
76,1.319424,1.564922,1.0,1.0,0.0,0.0,0.0
77,0.332554,1.564922,0.0,0.0,0.0,0.0,1.0
78,1.607261,0.521641,1.0,0.0,1.0,0.0,0.0


In [106]:
X_test_transformed

,age,fever,cough_strong,city_delhi,city_kolkata,city_mumbai,gender_male
0,-1.065510,1.564922,0.0,0.0,1.0,0.0,0.0
1,1.648380,-1.564922,0.0,1.0,0.0,0.0,1.0
2,1.031587,0.000000,1.0,1.0,0.0,0.0,0.0
3,1.196065,-1.043281,0.0,0.0,0.0,0.0,1.0
4,-0.942152,0.521641,1.0,1.0,0.0,0.0,1.0
5,0.291435,1.043281,0.0,0.0,1.0,0.0,0.0
6,1.154945,-1.564922,1.0,0.0,1.0,0.0,0.0
7,-1.188869,-1.043281,0.0,0.0,0.0,1.0,0.0
8,1.319424,0.000000,0.0,1.0,0.0,0.0,0.0
9,0.702630,1.043281,0.0,0.0,1.0,0.0,1.0


In [107]:
y_train_final = y_train_le
y_test_final = y_test_le

y_train_final

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1])

In [108]:
y_test_final

array([0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0])

In [109]:
# Feature Engineering is done. Now we can use these transformed features to train our model.